<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>Assets\WindowsCleanBooster.ico</ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>

		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<PublishTrimmed>false</PublishTrimmed>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<ApplicationIcon>Assets\WindowsCleanBooster.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
	  <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
	  <PackageReference Include="System.Management" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\" />
	</ItemGroup>

</Project>